# HostAtHome - Project Zomboid Server Configuration

__format__: ini

server:
  name:
    value: "HostAtHome Zomboid"
    key: PublicName
  description:
    value: "A Project Zomboid server"
    key: PublicDescription
  password:
    value: ""
    key: Password
  max-players:
    value: 16
    key: MaxPlayers
  admin-password:
    value: "admin"
    key: AdminPassword

gameplay:
  pause-empty:
    value: true
    key: PauseEmpty
  pvp:
    value: true
    key: PVP

world:
  map:
    value: "Muldraugh, KY"
    key: Map
